name: Deploy to TestFlight & Google Play

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get
        working-directory: ./Script Files

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: ./Script Files

      - name: Build iOS for TestFlight
        run: flutter build ios --release
        working-directory: ./Script Files
